####################################
# These configs allow this deployer to create a directory structure like this:
# project_root **e.g. "/srv/wsgi"
#             - project_name **e.g. "xls2xform_dev"
#                           - %{project}   ** the project code
#                           - project_env  ** a virtualenv for the python libraries
#                           - apache       ** configurations for wsgi and apache
#                           - logs         ** a place for apache logs
#                           - backups      ** a place for backups

#where your projects live:
project_root: /home/mvp/src

#the URL for this project
hostname: childcount.rapidsms
#the admin email (used in the apache config file)
admin_email: childcount-dev@googlegroups.com
#the user that the server will run as (used in the apache config)
server_user: www-data
# everything will be installed in "/%{project_root}/${install_name}"
install_name: childcount

#the repository's name (e.g. xyz.git => xyz)
git:
  name: childcount
  repo: git://github.com/mvpdev/rapidsms.git
  branch: ccstable

#python version (to be used in the virtualenv)
python_version: python2.6
